### Configurações Globais
@baseUrl = http://localhost:3001
@contentType = application/json

### 1. Criar Novo Usuário - Estudante (Dispara evento para a Comunidade)
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "rogerio2.restclientt@unisenai.com",
  "password": "senhaSegura123",
  "type": "student",
  "ra": "123453336",
  "periodo": 1
}

### 2. Criar Novo Usuário - Professor (Dispara evento para a Comunidade)
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "professor2.restclient@unisenai.com",
  "password": "senhaSegura123",
  "type": "professor",
  "matricula": "9876542",
  "titulacao": "Mestrado"
}

### 3. Obter posts do Community Service (Feed simulado)
GET http://localhost:3002/posts
Content-Type: application/json

### 4. Criar Post com Autor Válido (Fase 2)
POST http://localhost:3002/posts
Content-Type: application/json

{
  "title": "Minha publicação real no banco de dados",
  "content": "Este é o conteúdo do post que está sendo salvo fisicamente na comunidade usando o PrismaService.",
  "authorId": "ca5b1a23-ab4a-4edb-bf64-868921676de6"
}

### 5. Criar Post com Autor Inválido (Cenário de Erro 404 - Fase 2)
POST http://localhost:3002/posts
Content-Type: application/json

{
  "title": "Post que deve falhar",
  "content": "Este post não deve ser salvo porque o authorId não existe no banco.",
  "authorId": "00000000-0000-0000-0000-000000000000"
}